---
title: "Mapping CHNAs & CHIPs"
author: "Ohio University"
#format: revealjs
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    self-contained: true
    html-math-method: katex
    column: screen-inset
#    css: styles.css
editor_options: 
  chunk_output_type: console
---


```{r}
#| include: false  

knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, 
  fig.align = "center", fig.retina = 3, cache = FALSE
  )

library(tidyverse)

readxl::read_excel(
  "mappingOhioCHNA.xlsx"
  ) -> chnachip

chnachip %>%
  group_by(FIPS, org_type) %>%
  select(
    -appalachian
    ) %>%
  summarize(
    across(
      1:34,
      sum,
      na.rm = TRUE
      )
    ) -> df01

chnachip %>%
  select(
    -c(appalachian, org_type)
    ) %>%
  group_by(FIPS) %>%
  mutate(
    norgs = sum(n())
  ) %>% 
  relocate(FIPS, norgs) %>%
  group_by(FIPS, norgs) %>%
  summarize(
    across(
      1:34,
      sum,
      na.rm = TRUE
      )
    ) -> df02

library(tigris)
options(tigris_use_cache = TRUE)

counties(state = "OH", cb = TRUE, year = 2020) -> ohcts

ohcts %>%
  mutate(
    FIPS = as.numeric(GEOID)
    ) %>%
  left_join(
    df01,
    by = "FIPS"
    ) -> mydf01

ohcts %>%
  mutate(
    FIPS = as.numeric(GEOID)
    ) %>%
  left_join(
    df02,
    by = "FIPS"
    ) -> mydf02

c("Adams", "Ashtabula", "Athens", "Belmont", "Brown", "Carroll", "Clermont", "Columbiana", "Coshocton", "Gallia", "Guernsey", "Harrison", "Highland", "Hocking", "Holmes", "Jackson", "Jefferson", "Lawrence", "Mahoning", "Meigs", "Monroe", "Morgan", "Muskingum", "Noble", "Perry", "Pike", "Ross", "Scioto", "Trumbull", "Tuscarawas", "Vinton", "Washington") -> appalachian.ohio 

mydf02 %>%
  mutate(
    appalachia = case_when(
      NAME %in% appalachian.ohio ~ "Appalachian",
      TRUE ~ "Not Appalachian"
      )
    ) -> mydf02

```

## How often do they mention a particular need?



```{r, out.width="80%", fig.width = 12, fig.height=11}

#| column: screen-inset

mydf02 %>%
  group_by(appalachia) %>%
  select(
    appalachia, starts_with("n", ignore.case = FALSE)
  ) %>%
  sf::st_drop_geometry() -> mydf03

mydf03 %>%
  group_by(appalachia) %>%
    summarize(
    across(
      1:18,
      sum,
      na.rm = TRUE
      )
    ) -> mydf04

mydf04 %>%
  group_by(appalachia, norgs) %>%
  pivot_longer(
    names_to = "Issue",
    values_to = "Mentions",
    3:19
  ) -> mydf05

mydf05 %>%
  group_by(appalachia, Issue) %>%
  mutate(
    pct = round( (Mentions / norgs) * 100, digits = 1)
    ) -> mydf06

mydf06 %>%
  ungroup() %>%
  mutate(
    Issue = substring(Issue, 2)
  ) %>%
  filter(
    appalachia == "Appalachian"
  ) %>%
  ggplot() +
  geom_col(
    aes(
      x = pct, 
      y = forcats::fct_reorder(Issue, pct),
      fill = pct
    )
  ) +
  geom_text(
    aes(
      x = pct, 
      y = forcats::fct_reorder(Issue, pct),
      label = pct,
      hjust = -0.25
    ),
      color = "black"
  ) +
  xlim(0, 100) +
  hrbrthemes::theme_ipsum_rc() +
  scale_fill_continuous() +
  theme(legend.position = "none") +
  labs(title = 'Appalachian Counties',
       y = "",
       x = "Percent of Mentions") -> p1

mydf06 %>%
  ungroup() %>%
  mutate(
    Issue = substring(Issue, 2)
  ) %>%
  filter(
    appalachia == "Not Appalachian"
  ) %>%
  ggplot() +
  geom_col(
    aes(
      x = pct, 
      y = forcats::fct_reorder(Issue, pct),
      fill = pct
    )
  ) +
  geom_text(
    aes(
      x = pct, 
      y = forcats::fct_reorder(Issue, pct),
      label = pct,
      hjust = -0.25
    ),
      color = "black"
  ) +
  xlim(0, 100) +  
  hrbrthemes::theme_ipsum_rc() +
  scale_fill_continuous() +
  theme(legend.position = "none") +
  labs(title = 'Non-Appalachian Counties',
       y = "",
       x = "Percent of Mentions") -> p2

library(patchwork)
(p1 | p2)
```

```{r}

mydf02 %>%
  select(6, 14, 15:50) %>% 
  relocate(appalachia, NAME, norgs) %>% 
  group_by(appalachia, NAME, norgs) %>%
  pivot_longer(
    names_to = 'Issue',
    values_to = 'Values',
    4:37
  ) %>%
  group_by(appalachia, NAME, norgs, Issue) %>%
  mutate(
    pct = round( (Values / norgs) * 100, digits = 1)
  ) %>%
  separate(
    Issue,
    into = c("part1", "part2"),
    sep = 1
  ) %>%
  mutate(
    Type = case_when(
      part1 == "n" ~ "Needs Assessment",
      part1 == "i" ~ "Improvement Plan"
    )
  ) %>%
  select(-part1) %>%
  rename(
    Issue = part2
  ) -> mapdf01

```


## Mental Health

```{r mental-health, out.width = "100%", fig.width = 13, fig.height = 13}
#library(nat)

mapdf01 %>%
  filter(Issue == "Mental Health", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Mental Health", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Substance Use

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Substance Use/Abuse", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Substance Use/Abuse", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## Access

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Access", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Access", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Obesity, Nutrition, Inactivity

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Obesity/Nutrition/Inactivity", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Obesity/Nutrition/Inactivity", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Chronic Disease

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Chronic Disease", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Chronic Disease", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## Diabetes

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Diabetes", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Diabetes", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## Cancer

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Cancer", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Cancer", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## Senior Health

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Senior Health", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Senior Health", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Maternal and/or Child Health

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Maternal and/or Child Health", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Maternal and/or Child Health", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## Heart Disease

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Heart Disease", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Heart Disease", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Tobacco

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Tobacco", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Tobacco", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## SDOH & Disparities

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "SDOH + Disparities", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "SDOH + Disparities", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```


## Asthma

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Asthma", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Asthma", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Pediatric

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Pediatric", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Pediatric", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Infectious Disease

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Infectious Disease", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Infectious Disease", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Oral Health

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Oral Health", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Oral Health", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```

## Preventative Health

```{r, out.width = "100%", fig.width = 13, fig.height = 13}
mapdf01 %>%
  filter(Issue == "Preventative Health", Type == "Needs Assessment") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Needs Assessment"
    ) -> p1

mapdf01 %>%
  filter(Issue == "Preventative Health", Type == "Improvement Plan") %>%
  ggplot() +
  geom_sf(
    # aes(fill = cut_interval(`nMental Health`, 3)),
    aes(fill = pct),
    alpha = 0.8,
    size = 0.3,
    color = "white"
  ) +
  geom_sf_text(
    aes(label = NAME),
     size = 2, 
    color = ifelse(mydf02$appalachia != "Appalachian", "black", "white"),
  ) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    panel.background = element_blank(),
    line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(),
    legend.position = "bottom"
    ) + 
  coord_sf(datum = NA) +
  labs(
    fill = "Percent of Mentions"
    , title = "Improvement Plan"
    ) -> p2

(p1 | p2)

```
